package kilo

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"time"

	"github.com/entireio/external-agents/agents/entire-agent-kilo/internal/protocol"
)

// Hook name constants. These are passed as the second positional argument to
// `entire hooks kilo <hook>` by the Kilo plugin. They are intentionally
// kebab-case to match Entire's external-agent hook convention (the dotted
// Kilo native event names like `session.created` are translated by the plugin).
const (
	HookNameSessionStart = "session-start"
	HookNameTurnStart    = "turn-start"
	HookNameTurnEnd      = "turn-end"
	HookNameCompaction   = "compaction"
	HookNameSessionEnd   = "session-end"
)

const (
	pluginDir        = ".kilo/plugins"
	pluginFile       = ".kilo/plugins/entire.ts"
	pluginMarker     = "Auto-generated by `entire enable --agent kilo`"
	transcriptSubdir = "kilo"
)

// sessionInfoRaw is the payload shape for session-start, session-end, and
// compaction hooks. The plugin sends only the session_id; the Kilo session
// JSON is expected to already be on disk (the turn-end hook writes it).
type sessionInfoRaw struct {
	SessionID string `json:"session_id"`
}

// turnStartRaw is the payload for turn-start. Carries the user prompt + model
// captured at message.part.updated time.
type turnStartRaw struct {
	SessionID string `json:"session_id"`
	Prompt    string `json:"prompt"`
	Model     string `json:"model"`
}

// turnEndRaw is the payload for turn-end. Plugin writes the full session JSON
// to session_ref before invoking; the Go binary verifies the file landed and
// emits a TurnEnd event with the model captured at session.status time.
type turnEndRaw struct {
	SessionID string          `json:"session_id"`
	Model     string          `json:"model"`
	Session   json.RawMessage `json:"session,omitempty"`
	Messages  json.RawMessage `json:"messages,omitempty"`
}

func (a *Agent) ParseHook(hookName string, input []byte) (*protocol.EventJSON, error) {
	if len(input) == 0 {
		return nil, nil
	}

	now := time.Now().UTC().Format(time.RFC3339)

	switch hookName {
	case HookNameSessionStart:
		var raw sessionInfoRaw
		if err := json.Unmarshal(input, &raw); err != nil {
			return nil, fmt.Errorf("parse session-start payload: %w", err)
		}
		if raw.SessionID == "" {
			return nil, nil
		}
		return &protocol.EventJSON{
			Type:       1,
			SessionID:  raw.SessionID,
			SessionRef: transcriptPath(raw.SessionID),
			Timestamp:  now,
		}, nil

	case HookNameTurnStart:
		var raw turnStartRaw
		if err := json.Unmarshal(input, &raw); err != nil {
			return nil, fmt.Errorf("parse turn-start payload: %w", err)
		}
		if raw.SessionID == "" {
			return nil, nil
		}
		return &protocol.EventJSON{
			Type:       2,
			SessionID:  raw.SessionID,
			SessionRef: transcriptPath(raw.SessionID),
			Prompt:     raw.Prompt,
			Model:      raw.Model,
			Timestamp:  now,
		}, nil

	case HookNameTurnEnd:
		var raw turnEndRaw
		if err := json.Unmarshal(input, &raw); err != nil {
			return nil, fmt.Errorf("parse turn-end payload: %w", err)
		}
		if raw.SessionID == "" {
			return nil, nil
		}
		sessionRef := transcriptPath(raw.SessionID)
		// Plugin may bundle the session snapshot in the payload (for instances
		// where the plugin can't write to disk itself). Persist it to session_ref
		// so downstream transcript operations see a populated file.
		if len(raw.Session) > 0 || len(raw.Messages) > 0 {
			if err := writeSessionPayload(sessionRef, raw.Session, raw.Messages); err != nil {
				return nil, fmt.Errorf("write session ref on turn-end: %w", err)
			}
		}
		model := raw.Model
		if model == "" {
			model = latestModelFromSessionRef(sessionRef)
		}
		return &protocol.EventJSON{
			Type:       3,
			SessionID:  raw.SessionID,
			SessionRef: sessionRef,
			Model:      model,
			Timestamp:  now,
		}, nil

	case HookNameCompaction:
		var raw sessionInfoRaw
		if err := json.Unmarshal(input, &raw); err != nil {
			return nil, fmt.Errorf("parse compaction payload: %w", err)
		}
		if raw.SessionID == "" {
			return nil, nil
		}
		return &protocol.EventJSON{
			Type:       4,
			SessionID:  raw.SessionID,
			SessionRef: transcriptPath(raw.SessionID),
			Timestamp:  now,
		}, nil

	case HookNameSessionEnd:
		var raw sessionInfoRaw
		if err := json.Unmarshal(input, &raw); err != nil {
			return nil, fmt.Errorf("parse session-end payload: %w", err)
		}
		if raw.SessionID == "" {
			return nil, nil
		}
		return &protocol.EventJSON{
			Type:       5,
			SessionID:  raw.SessionID,
			SessionRef: transcriptPath(raw.SessionID),
			Timestamp:  now,
		}, nil

	default:
		return nil, nil
	}
}

// writeSessionPayload persists the messages from a turn-end hook payload. The
// plugin sends messages in the "messages" field; older/blob payloads may carry
// them inside "session" instead. Stored as one-message-per-line JSONL so
// Entire's line-based transcript scoping lands on message boundaries.
func writeSessionPayload(sessionRef string, sessionRaw, messagesRaw json.RawMessage) error {
	if strings.TrimSpace(sessionRef) == "" {
		return errors.New("session_ref is required")
	}
	if err := os.MkdirAll(filepath.Dir(sessionRef), 0o750); err != nil {
		return err
	}

	var messages []SessionMessage
	switch {
	case len(messagesRaw) > 0:
		if err := json.Unmarshal(messagesRaw, &messages); err != nil {
			return fmt.Errorf("parse messages payload: %w", err)
		}
	case len(sessionRaw) > 0:
		parsed, err := parseKiloExport(sessionRaw)
		if err != nil {
			return err
		}
		messages = parsed
	}

	// Never overwrite an existing transcript with an empty one. A failed
	// snapshot on the plugin side sends messages:[]; clobbering here would
	// destroy the last good transcript. Leave the existing file for
	// prepare-transcript / the next turn to refresh.
	if len(messages) == 0 {
		return nil
	}

	encoded, err := encodeMessagesJSONL(messages)
	if err != nil {
		return fmt.Errorf("encode session: %w", err)
	}
	return atomicWriteFile(sessionRef, encoded, 0o600)
}

// latestModelFromSessionRef returns the most recent assistant model recorded
// in the prepared session JSON at sessionRef.
func latestModelFromSessionRef(sessionRef string) string {
	if strings.TrimSpace(sessionRef) == "" {
		return ""
	}
	data, err := os.ReadFile(sessionRef)
	if err != nil || len(bytes.TrimSpace(data)) == 0 {
		return ""
	}
	messages, err := decodeTranscript(data)
	if err != nil {
		return ""
	}
	return latestSessionModel(messages)
}

func (a *Agent) InstallHooks(localDev bool, force bool) (int, error) {
	root := protocol.RepoRoot()

	cmdPrefix := "entire"
	if localDev {
		cmdPrefix = `go run "$(git rev-parse --show-toplevel)"/cmd/entire/main.go`
	}
	content := strings.ReplaceAll(generatePlugin(), entireCmdPlaceholder, cmdPrefix)

	path := filepath.Join(root, pluginFile)
	if !force {
		if existing, readErr := os.ReadFile(path); readErr == nil && string(existing) == content {
			return 0, nil
		}
	}

	dir := filepath.Join(root, pluginDir)
	if err := os.MkdirAll(dir, 0o750); err != nil {
		return 0, fmt.Errorf("create plugin dir: %w", err)
	}
	if err := os.WriteFile(path, []byte(content), 0o600); err != nil {
		return 0, fmt.Errorf("write plugin: %w", err)
	}

	return 1, nil
}

func (a *Agent) UninstallHooks() error {
	root := protocol.RepoRoot()
	path := filepath.Join(root, pluginFile)
	if err := os.Remove(path); err != nil && !os.IsNotExist(err) {
		return err
	}
	dir := filepath.Join(root, pluginDir)
	if entries, err := os.ReadDir(dir); err == nil && len(entries) == 0 {
		_ = os.Remove(dir)
	}
	kiloDir := filepath.Join(root, ".kilo")
	if entries, err := os.ReadDir(kiloDir); err == nil && len(entries) == 0 {
		_ = os.Remove(kiloDir)
	}
	return nil
}

func (a *Agent) AreHooksInstalled() bool {
	root := protocol.RepoRoot()
	data, err := os.ReadFile(filepath.Join(root, pluginFile))
	return err == nil && strings.Contains(string(data), pluginMarker)
}

// fetchSession is reserved for mid-turn refresh from the Kilo HTTP server.
// Kilo's CLI does not currently expose a `kilo export` equivalent, so the
// production transcript path is the plugin write-on-turn-end. This method
// remains as a future hook for a Bun-based refresh subprocess.
func (a *Agent) fetchSession(sessionID, sessionRef string) error {
	if strings.TrimSpace(sessionID) == "" || strings.TrimSpace(sessionRef) == "" {
		return errors.New("session id and session ref are required")
	}
	runner := a.CommandRunner
	if runner == nil {
		runner = &DefaultCommandRunner{}
	}
	if err := os.MkdirAll(filepath.Dir(sessionRef), 0o750); err != nil {
		return err
	}
	ctx, cancel := context.WithTimeout(context.Background(), prepareTranscriptTimeout)
	defer cancel()

	// Export Kilo's native session blob and store it as one-message-per-line
	// JSONL so downstream scoping works (session_jsonl.go).
	raw, err := runner.ExportSession(ctx, sessionID)
	if err != nil {
		return err
	}
	messages, err := parseKiloExport(raw)
	if err != nil {
		return err
	}
	encoded, err := encodeMessagesJSONL(messages)
	if err != nil {
		return err
	}
	return atomicWriteFile(sessionRef, encoded, 0o600)
}

const entireCmdPlaceholder = "__ENTIRE_CMD__"

func generatePlugin() string {
	return `// Entire CLI plugin for Kilo Code
// ` + pluginMarker + `
// Do not edit manually — changes will be overwritten on next install.
// Requires Bun runtime (used by Kilo's plugin system for loading ESM plugins).
import type { Plugin } from "@kilocode/plugin"

export const EntirePlugin: Plugin = async ({ directory }) => {
  const ENTIRE_CMD = '__ENTIRE_CMD__'
  const seenUserMessages = new Set<string>()
  let currentSessionID: string | null = null
  let currentModel: string | null = null
  const messageStore = new Map<string, any>()
  const announcedSessions = new Set<string>()

  function hookCmd(hookName: string): string[] {
    if (ENTIRE_CMD !== "entire") {
      return ["sh", "-c", ` + "`${ENTIRE_CMD} hooks kilo ${hookName}`" + `]
    }
    return ["sh", "-c", ` + "`if ! command -v entire >/dev/null 2>&1; then exit 0; fi; exec entire hooks kilo ${hookName}`" + `]
  }

  async function callHook(hookName: string, payload: Record<string, unknown>) {
    try {
      const json = JSON.stringify(payload)
      const proc = Bun.spawn(hookCmd(hookName), {
        cwd: directory,
        stdin: new Blob([json + "\n"]),
        stdout: "ignore",
        stderr: "ignore",
      })
      await proc.exited
    } catch {
      // Silently ignore — plugin failures must not crash Kilo.
    }
  }

  function callHookSync(hookName: string, payload: Record<string, unknown>) {
    try {
      const json = JSON.stringify(payload)
      Bun.spawnSync(hookCmd(hookName), {
        cwd: directory,
        stdin: new TextEncoder().encode(json + "\n"),
        stdout: "ignore",
        stderr: "ignore",
      })
    } catch {
      // Silently ignore — plugin failures must not crash Kilo.
    }
  }

  function resetSessionTracking(sessionID: string) {
    if (currentSessionID === sessionID) {
      return false
    }
    seenUserMessages.clear()
    messageStore.clear()
    currentModel = null
    currentSessionID = sessionID
    return true
  }

  return {
    event: async ({ event }) => {
      try {
        switch (event.type) {
          case "session.created": {
            const session = (event as any).properties?.info
            if (!session?.id) break
            // Sub-sessions are tracked by Kilo too; only top-level ones get an
            // Entire SessionStart.
            if (session.parentID) break
            if (announcedSessions.has(session.id)) break
            announcedSessions.add(session.id)
            if (resetSessionTracking(session.id)) {
              callHookSync("session-start", { session_id: session.id })
            }
            break
          }

          case "message.updated": {
            const msg = (event as any).properties?.info
            if (!msg) break
            if (msg.sessionID && resetSessionTracking(msg.sessionID) && !announcedSessions.has(msg.sessionID)) {
              announcedSessions.add(msg.sessionID)
              callHookSync("session-start", { session_id: msg.sessionID })
            }
            messageStore.set(msg.id, msg)
            if (msg.role === "assistant" && msg.modelID) {
              currentModel = msg.modelID
            }
            // Turn-start fires from the text part (message.part.updated), which
            // carries the actual prompt. Firing here with an empty prompt would
            // mark the message seen and suppress the real one, dropping prompts.
            break
          }

          case "message.part.updated": {
            const part = (event as any).properties?.part
            if (!part?.messageID) break
            const msg = messageStore.get(part.messageID)
            if (msg?.role === "user" && part.type === "text" && !seenUserMessages.has(msg.id)) {
              seenUserMessages.add(msg.id)
              const sessionID = msg.sessionID ?? currentSessionID
              if (sessionID) {
                callHookSync("turn-start", {
                  session_id: sessionID,
                  prompt: part.text ?? "",
                  model: currentModel ?? "",
                })
              }
            }
            break
          }

          case "session.status": {
            // session.status fires reliably in both TUI and ` + "`kilo run`" + ` mode.
            // session.idle is deprecated upstream and not always emitted on run exit.
            const props = (event as any).properties
            if (props?.status?.type !== "idle") break
            const sessionID = props?.sessionID ?? currentSessionID
            if (!sessionID) break
            // Fire turn-end synchronously — kilo run exits on this same idle
            // event, so an awaited async fetch here can be cancelled before the
            // hook runs. Entire materializes the transcript on its side via
            // prepare-transcript (kilo session show), which reads Kilo's
            // persisted store and is authoritative regardless of process exit.
            callHookSync("turn-end", {
              session_id: sessionID,
              model: currentModel ?? "",
            })
            break
          }

          case "session.compacted": {
            const sessionID = (event as any).properties?.sessionID
            if (!sessionID) break
            await callHook("compaction", { session_id: sessionID })
            break
          }

          case "session.deleted": {
            const session = (event as any).properties?.info
            if (!session?.id) break
            seenUserMessages.clear()
            messageStore.clear()
            announcedSessions.delete(session.id)
            currentSessionID = null
            callHookSync("session-end", { session_id: session.id })
            break
          }

          case "server.instance.disposed": {
            // Fires on Kilo shutdown (TUI close or ` + "`kilo run`" + ` exit).
            // session.deleted only fires on explicit user deletion, so this is
            // the only reliable terminator on process exit.
            if (!currentSessionID) break
            const sessionID = currentSessionID
            seenUserMessages.clear()
            messageStore.clear()
            announcedSessions.delete(sessionID)
            currentSessionID = null
            callHookSync("session-end", { session_id: sessionID })
            break
          }
        }
      } catch {
        // Silently ignore — plugin failures must not crash Kilo.
      }
    },
  }
}

export default { id: "entire-agent-kilo", server: EntirePlugin }
`
}

func transcriptPath(sessionID string) string {
	return filepath.Join(protocol.DefaultSessionDir(protocol.RepoRoot()), transcriptSubdir, safeSessionID(sessionID)+".json")
}

func safeSessionID(sessionID string) string {
	if sessionID == "" {
		return "unknown"
	}
	re := regexp.MustCompile(`[^A-Za-z0-9_.-]+`)
	return re.ReplaceAllString(sessionID, "_")
}
